export const DREWS_PITCH_AUDIO_ID = '2843f285-ef81-4941-9ce9-327de7364865';

export const DREWS_PITCH_SUMMARY = `## Executive Summary
Drew, an established Jellyfish Lighting dealer operating in the Cincinnati market, met with Samuel and the corporate leadership team to pitch a turnkey sales, CRM, and marketing system for dealers across the country.

Drew shared his proven sales methodology, September financial metrics (nearly 10x ROI on Meta ad spend), lead handling process with custom home renderings, and customer closing techniques. The conversation centered on bridging the gap between Jellyfish's hardware product and the sales/business execution of independent dealers.

### Key Metrics (Cincinnati Dealership)
- **Meta Ad Spend (Sept):** $11,000
- **Net Sales Volume (Sept):** $109,000 (~9.9x ROI / ROAS)
- **Inbound Leads Generated:** 100+ leads
- **Issued Consultations:** 20–25 appointments
- **Closed Jobs:** 10–13 sales (~50% close rate on appointments)
- **Average Contract Value:** $6,500 – $6,800
- **Retail Pricing:** $54 / linear foot (100 ft = $5,400)
- **Par / Minimum Price:** 65% of retail + $1,000 (strict floor price)
- **Q4 Projected Ad Spend:** $18,000 – $23,000/mo (scaling for holiday demand)
- **Google Reviews:** 4.8 – 4.9 Stars (80+ reviews over 3 years)

### Core Discussion Highlights
1. **Speed-to-Lead & Custom Renderings:** Instant automated SMS & email upon form submission. Sales rep follows up immediately with a custom rendering of the customer's actual home exterior illuminated with Jellyfish lights.
2. **Turnkey CRM:** $50–$100/mo automated CRM handling pipeline stages, lead capture, and immediate notifications.
3. **Dealer Education:** Corporate is developing an education system to train incoming craftsmen dealers on sales, marketing, and business management. Testing Dialpad for dealer phone infrastructure.

### Next Steps & Action Items
1. Samuel to brief Max and Jeff on Drew's pitch and CRM system.
2. Coordinate follow-up call in 1–2 days to review radius and county mapping across 5 target zones.
3. Coordinate bringing Drew out to Utah early-to-mid next month for a 1–2 day working session.`;

export const DREWS_PITCH_TRANSCRIPT = `Drew: What a horrible idea. [laughs] And then, the... there was a few that I talked to that do buy the leads, or do spend the money. You're not really buying the leads, but they do spend the money to generate the leads. And then the one guy was just like, you know, "Yeah, it's where I get most of our business at, but you know, having time to mess with them... I've probably got 40 leads sitting on my desk right now I haven't called." [laughter]

Drew: And you know, what... The meeting out there, it... So my take on, you know, Jellyfish corporate... I think you guys have got a great product. I think you've got phenomenal resources as far as like what you offer with the marketing, what you offer as far as your tech support. But as far as like the... getting people started, the sales side, the... you know, even like setting them up to be successful with the leads that come in... If, like, I had somebody last year, it was their full-time job to just sit and call the leads. And I mean, that alone was a full-time job. And we weren't spending... I mean, we weren't even spending a third of what we're going to spend this year.

Samuel: Yeah.

Drew: Honestly, I didn't know that we were allowed to spend more than $3,000 a month last year when I first started. It says, you know, $3,000, so I was just like, "Oh, okay. Well, that's what you spend." And you had sent something out and it was like... It wasn't even $3,000, it was $4,500, but it included like the Google as well, but you had to do it for like a three-month minimum and... I don't remember exactly what it was, but I didn't realize we could spend more or less until later on. And that's actually, you know, a lot of the remarketing and just Facebook in general is what I had asked Michael about initially. And that's when he sent me Max's phone number and said just give him a call. So that's what I was actually reaching out about, the conversation we're having right now. This was just an observation and I didn't really know, like I didn't say anything because I didn't feel like it was my place.

Drew: And then there was a company who was looking to recruit dealers for another product, not anything with like lighting or anything like that. But their... everything about their product and how they do business, everything like really appealed to me. And I reached out to them, and when I got off the phone with the guy, I was like, "Man, if Jellyfish did it like this, like it would be better for everyone." But again, I didn't really have... I wasn't even going to say anything. And then Michael mentioned, you know, the possibility of like a Jellyfish of Cincinnati type of situation. And you know, what I told Michael was like, I think that would be awesome, but there's too many things I can't control and I know how hard it is to generate a good reputation. We've been trying like hell for three years, and you know, we've got a 4.8 or 4.9 star Google review on like 80-something reviews. And then look at the bad reviews that we've had. We've had three in three years, and they had absolutely nothing to do with us. One wasn't our customer. [laughter] One was a customer that didn't even buy, like we never even went out to her house. She had another company out and I guess she thought we were them, so she left us a bad review.

Samuel: Gotcha.

Drew: And you know, my concern is I don't know all of your dealers, but I do know a few of the dealers that you have here in Cincinnati that I've worked with in the past. One of the dealers, he was my mentor, he brought me into the game. Love him to death, but the way he runs his company... you know, it's not how I would run a company. He's located in Ohio and he's got like 10 or 12 offices across the country and everything gets run remote. There are no like physical locations, there's no dedicated crews, there's no dedicated project managers. So like even if a customer... usually customers have to wait quite a while before they get their install, and God forbid it didn't go in right, if there's a problem, like it may never get fixed.

Drew: They basically said like, "Hey, if you follow our system, this is what the dealers are doing, this is what the average is, this is the highs, this is the lows." And it made it to where they were actually able to be selective as to who they brought on. And I told Michael, I was like, "I don't know how many dealers you guys have, but it wouldn't surprise me if you've got 800 or 1,000 dealers across the country." But if you could, you know, put however many people you have to the side now and just look at the bare numbers of it all... If you had, let's just say 400 dealers instead of, you know—and again, I don't know how many you got, but I'm betting 800 is probably a low number—but if you just had half that, you had 400, but they were required to do just like the bare minimum at $3,000 a month in ad spend, that would put you guys in a spot where you're managing bare minimum, not even counting your own accounts, you'd be managing $1.2 million worth of ad spend per month. And maybe you already managed that much, I have no idea. But I'm fairly certain the more money you're spending, the better it has to be, right? For your lookalike audience and just everything in general. But anyway...

Samuel: Mhm.

Drew: Michael said that a big reason they didn't have something already like that set up was the upfront cost of a CRM, the hassle of everything. And that's when I told him like, "Well, I've got a CRM that they could get into for probably right around $50 to $100 bucks a month that would be managed for them. It would link directly to the leads that you guys are generating. It comes in, and as soon as the lead comes in, it's being contacted immediately." We've got that set up for us. It wouldn't be incredibly difficult. But you can't rely on just... like if all I had was the CRM and I didn't have like an actual sales presentation put together for the customers when we go out to their homes, you know, that would be difficult. Right now we generate—I don't know, what did we generate last week with Facebook, 100-and-something leads? Of the 100 leads we generated, well maybe issue 20, 25 of them. Fortunately, if we issue 25, we'll probably sell somewhere in the neighborhood of 10 to 13 of them. And our average sale is like $6,500, $6,800 bucks.

Samuel: Mhm.

Drew: A lot of the guys that I talked to last year, the number they start out at, like that they just kind of try to sell at, is a number lower than what we'll even consider selling at.

Samuel: Yeah.

Drew: So last year, we wouldn't sell below... We didn't sell a single job below par. Par is 65% of retail plus $1,000, and our retail was $54 a foot. So you take a 100-foot job, retail on that's $5,400, minus 65% of that puts you right... If you could, when you're bringing a dealer on, be able to not just show them how to install it and the different cuts, but like show them how to run a business, how to market the product, what to do with the leads once you generate the leads, then how to sell the leads... You guys have the install portion figured out phenomenally.

Samuel: Yeah. I was going to say, um, as I'm sitting here listening to you... I know that some of the things related to the structure, kind of where we're at, you know, we have to make that decision internally as to how we manage our... you know, the size and scope of dealers that we bring. You know, we do have obviously control over, you know, bringing more or less people into Cincinnati, and I definitely can bring fewer people into Cincinnati or stop for a period of time bringing people into Cincinnati to help you and give you some space to grow and all of that. The stuff that really intrigues me is the stuff that you're talking about. This is where I thought that Max and Samuel and you kind of talking to them and getting a feel for kind of what exactly you were presenting was related to, you know, the CRM and some of the things that you were talking about about managing your leads and sales and integrating them and automating them and all of those things that would help them. Us as a company, we actually have been discussing a lot of these things. We've been in the middle of putting together... it's been coming slow, but we've been working on it, putting together like an education system for our dealers to better equip them with a more diverse information, like you're mentioning, whether it's marketing or sales or operating your business or any of those types of things related to Jellyfish Lighting. Because we do realize we've got people that come in with varying skills and abilities, and some need that, and some need a lot of those different things. Oftentimes when we're in this field, we have some people that come in with entrepreneurship and business experience, ownership, sales experience like you, and a lot of times we also end up with dealers coming in who are just craftsmen. And they don't have any of those things. Like we were talking about a guy today, we have a little meeting each morning and Shane was talking about him saying the guy was just giving, you know, he kind of would call on the phone and give the person a quote over the phone, and then wonder why nobody's buying from him! And his whole process was... there was never a sense of urgency, never a sense of reaching out to them within a certain amount of time, always just giving a quote over the phone and never following up, and always wondering why nobody's turning around and purchasing! You know, he just has no sales system in place and no formula for actually generating sales.

Samuel: So we definitely know that it's a weakness in what we do as far as providing content and support for dealers, but it's definitely something that we've been trying to add and contribute more and more to as we've grown. We've had more resources to be able to do so as well.

Team Member: Yeah, we do have marketing training and sales training on the Dealer Hub, but you're right, on the onboarding we don't...

Samuel: But even the marketing and sales training we have on the Dealer Hub is... it's pretty superficial still. You know, it's like "Here are a few resources, here are some suggestions," but what our discussions have been trying to gear more towards is a turn-key...

Drew: April, I think it was April, May, and June... I learned the hard way. I put way too many eggs in my Jellyfish basket. Increased our ad spend to an amount that it shouldn't have been anywhere near what we were spending. And then... and I did it because when we left the Jellyfish conference, like I was... you know, I was convinced that, for the most part, it sounds like you guys don't really do in-home sales, you do over-the-phone sales. And you know, I believe in speed-to-lead, whether it's over the phone or in home or whatever the case may be, speed-to-lead is going to be your... it's going to be important either way. But what we tried to do was we tried to basically use that... the system that we've created that we're using now, but instead of it being an AI, we tried to use real people, like actual sales reps. And we went so far as to, on our initial contact... it wasn't the very first message, the very first message came to them immediately. So as soon as we got the lead, they got their initial message and their initial email. And then they would get an email shortly thereafter from one of the actual reps introducing themselves: "Hi, this is John. I'm your Jellyfish permanent exterior lighting designer. I took the liberty of creating a rendering of what your home would look like, or could look like, with the lights on your home. I hope you like it." And then we would literally take the time to create this rendering and sent it to every single lead we got. And a lot of them would respond back, but 95% of the customers who did respond back had zero interest in us scheduling a time to come out to the home. They had zero interest in really anything other than a price over the phone. And it was... I mean, it was bad. But that's when I learned, like we didn't sell Jellyfish last year in those months. We didn't even attempt to sell anything until probably maybe July, and we didn't really get serious about it until like August, September. So from our point of view, every single month, we did more and more business. So we did more business in July than we did in June, doubled up in August, doubled up in September. Every month it continued to get better and better. So that's what led me to believe like, hey, if we just increase the ad spend, generate more leads... We didn't see that it would fall off like that.

Samuel: Yeah, and some of that is... you know, possibly us maybe articulating trends a little bit better. And that I think is a lot goes into like what we were talking about strategy and things like that. And so even with us, we don't stop marketing in those months. We actually market pretty significantly, we just market typically at a little bit higher percentage of sales during those slower months. But we try to maintain a certain number of crews year-round, and so we've always got... we always have to have sales, and so we always have to have leads. They just cost a little bit more that time of year. So Max and Samuel would have to look at it to kind of know maybe how our close ratios change during that period of time. That's where a conversation with Max and kind of understanding even real specifically maybe what percentage we allocate to marketing in peak months and off-peak months... Because I know he knows all those numbers off the top of his head. How you know that, Drew?

Drew: Not the corporate side as much.

Samuel: And the corporate side's probably a really good trend because we don't see what our dealers do. I mean, we know that they mark up with us, but since we don't see their books, we don't know how it affects their business. We don't know kind of what percentages they're doing. But we do have our corporate locations, and they are scattered across the country, so we get kind of a wide variety of results. And they definitely demonstrate strengths and weaknesses around the country, and they're definitely adjustments we have to do in different areas based on the lead flow or activity and interest in different areas. But we do have that year-over-year experience of doing that that gives you... that would give you... Max would probably be able to provide some information on that that would allow you to kind of see how that business changes and how we adapt to it.

Drew: Yeah, definitely could. And then also just the cost per leads that we get every month. We kind of showed that in the dealer conference, but we could host those...

Samuel: And then as far as like adapting a CRM, usually somebody like Max, and Haley, and Samuel have usually get involved in it and go through some testing on it and see kind of where the strengths and weaknesses are, you know, where we can, if we can, integrate everything like that.

Drew: Looked a lot into CRMs for dealers.

Samuel: Samuel right now has been looking into... You know, we want to change our phone system, so he's been doing a bunch of testing with Dialpad as something that we've been considering switching, just internal phone numbers for the dealer team too, so that we have something that's a little bit more reliable and we have better control over it, just general phone calls. But it's kind of gotten big enough that David wants us to jump through the hoops and make sure we're making the best decision. And I think whenever everything that comes down to software, I think David takes Max's opinion the highest.

Drew: Agreed! [laughter] Definitely.

Samuel: Max carries a lot of weight as far as those decisions go. And us as a dealer team, you know, Jeff and I, if we kind of knew what it was and we could go and test it and see how it could potentially integrate as well, would actually help also. So maybe it might be good to try to get all four of us. And so what I'd like to do is I'd like me and Samuel to go and talk to Max and see about... and kind of see maybe what it looks like as far as... because some of it I don't know if there's things in place that they feel like they can or can't break, or if it's just something that would just go to dealers. If it's something that goes just to dealers, there's... I think that anything can be broken and anything can be changed and altered, it's just a matter of, you know, making a decision to bring it on and implement it.

Drew: Yeah. Well, I'd be happy to sit down with you guys and show you how it works. I mean, I've been testing it here and just for y'all's information—and this isn't like a "look what we did"—but if I'm not mistaken, I believe our ad spend for the month of September was right at about $11,000, like with Meta, with you guys. And technically with the... what do you call the marketing... how you give 15%, the credits, yeah, with the credits it was about $2,400 less than that, but assuming there was no credit, I believe we spent right at $11,000. And we are at—and we've still got a couple days to go—but we're at, on that $11,000, we're at $109,000 as far as our net sales volume.

Samuel: Yeah.

Drew: So I mean, that's... we're pushing damn near a 10x. We were in the 8 to 10x all last year as well. And quite honestly, I think we've still got a hell of a lot of room for improvement. I think especially the next two months, you'll probably see that improve because it seems like people's pocketbooks open, your close rate will probably increase, and... Yeah, well, and that's why we're going to spend considerably more on our marketing in October and November and December. But yeah, so...

Samuel: Well, how about we do this? How about you let Samuel and I kind of talk to Jeff and Max about it, and let's see if there's a time we can talk or if maybe it warrants you coming out and chatting with us in person. Just make sure we can kind of coordinate something. I don't want you to come out here in vain if somebody thinks something's like... that like there's no possibility of it. So I would like to...

Drew: Yeah, I mean if it's something that they're totally not interested in... Well, it's not going to be a waste of my time. I really like Utah, so! [laughter] I would be more than happy to come out for a day or two early next month, middle of next month, something like that. And then I can actually show you exactly what it is that I'd like to, you know, offer to help with.

Samuel: Okay. Okay.

Drew: But yeah, if you talk to the guys and they're like, "Nah, we don't need that," then no big deal. But if there's any interest at all, like I said, I'm more than happy to fly out. It's a cheap, easy, quick flight for me, and I use my miles for everything, so it won't cost me a dime. [laughter]

Samuel: Yeah, yeah! So let us talk to them, let us make sure that we've got their support, and then if so, we'll kind of coordinate that with you and then get back with you shortly to coordinate that, okay?

Drew: Sounds good. And like I said, I'm going to be... I'll be calling you probably not today, I got to go pick my son up here soon, but probably tomorrow or the next day. I will reach out if you could let me know when will be a good time. I just... I've got a map up here, like a radius map tool. And again, you know, I know sales, but I don't know a whole lot about marketing. So I just want to make sure that when like I'm putting these zones together as to like where we want to spend money and how to do it, I just want to make sure that there's not a better way. So I don't want to spend a bunch of time putting something together...

Samuel: Totally.

Drew: ...because we're going to probably bump our ad spend up to somewhere in that $18,000 to $23,000 for next month. Again, I don't know if it's better to target by county, if it's better to do bigger radiuses and less, because like right now I think we've got it broken up between like five different areas and they overlap a little bit. But again, I'll give you a call here in the next day or two to talk about that and see what your thoughts are, and whatever you think is the best solution, that's the route we'll go.

Samuel: Sounds like a plan. Look forward to hearing from you.

Samuel: Hey, thanks for your time, Drew. Appreciate it.

Drew: Hey, no problem. Thank you. Y'all take it easy, see ya. Bye.`;
